# **Lecture du fichier**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("/content/dataset_planification_transport_LK.csv")
df.head()

,trajet_id,ville_depart,ville_arrivee,distance_km,duree_prevue_h,retard_min,prix_billet,nb_passagers,capacite_bus,type_bus,jour_semaine,periode_depart,condition_route,carburant_litre,satisfaction_client
0,1,Tsévié,Tsévié,56.0,7.2,163.0,8847.0,52.0,50.0,Climatisé,Dimanche,Après-midi,Bonne,43.4,3
1,2,Sokodé,Tsévié,NaN,2.9,124.0,9401.0,39.0,NaN,Standard,Dimanche,NaN,Moyenne,73.7,4
2,3,Dapaong,Sokodé,496.0,1.6,163.0,9228.0,56.0,NaN,Standard,Dimanche,Soir,Bonne,26.5,2
3,4,Sokodé,Lomé,463.0,8.8,88.0,3618.0,NaN,NaN,VIP,Jeudi,Matin,Mauvaise,42.5,4
4,5,Kara,Dapaong,130.0,3.4,32.0,7518.0,67.0,50.0,VIP,Dimanche,Après-midi,Mauvaise,21.5,1

# **Vérifier dimensions**

In [4]:
df.shape

(2000, 15)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   trajet_id            2000 non-null   int64
 1   ville_depart         1844 non-null   object
 2   ville_arrivee        1840 non-null   object
 3   distance_km          1840 non-null   float64
 4   duree_prevue_h       1840 non-null   float64
 5   retard_min           1840 non-null   float64
 6   prix_billet          1840 non-null   float64
 7   nb_passagers         1836 non-null   float64
 8   capacite_bus         1840 non-null   float64
 9   type_bus             1840 non-null   object
 10  jour_semaine         1840 non-null   object
 11  periode_depart       1840 non-null   object
 12  condition_route      1840 non-null   object
 13  carburant_litre      1840 non-null   float64
 14  satisfaction_client  2000 non-null   int64
dtypes: float64(7), int64(2), object(6)
memory usage: 234.5+ KB

# **Aperçu statistique**

In [6]:
df.describe()

,trajet_id,distance_km,duree_prevue_h,retard_min,prix_billet,nb_passagers,capacite_bus,carburant_litre,satisfaction_client
count,2000.000000,1840.000000,1840.000000,1840.000000,1840.000000,1836.000000,1840.000000,1840.000000,2000.00000
mean,1000.500000,352.983696,6.775326,91.687500,6726.460326,37.994009,50.315217,47.511196,2.99750
std,577.494589,173.609929,2.975420,51.889587,3071.395956,19.120825,13.968371,18.564397,1.39695
min,1.000000,50.000000,1.500000,0.000000,1528.000000,5.000000,30.000000,15.000000,1.00000
25%,500.750000,203.000000,4.200000,48.000000,4008.000000,21.000000,40.000000,31.575000,2.00000
50%,1000.500000,355.000000,6.900000,93.000000,6599.000000,39.000000,50.000000,47.350000,3.00000
75%,1500.250000,503.000000,9.300000,137.000000,9527.000000,54.000000,60.000000,63.500000,4.00000
max,2000.000000,649.000000,12.000000,179.000000,11997.000000,79.000000,70.000000,80.000000,5.00000

# **Vérifier taux de valeurs manquantes**

In [7]:
df.isna().mean()*100

trajet_id              0.0
ville_depart           7.8
ville_arrivee          8.0
distance_km            8.0
duree_prevue_h         8.0
retard_min             8.0
prix_billet            8.0
nb_passagers           8.2
capacite_bus           8.0
type_bus               8.0
jour_semaine           8.0
periode_depart         8.0
condition_route        8.0
carburant_litre        8.0
satisfaction_client    0.0
dtype: float64

#**Nettoyage des données**

In [8]:
# Supprimer les doublons
df.drop_duplicates()

,trajet_id,ville_depart,ville_arrivee,distance_km,duree_prevue_h,retard_min,prix_billet,nb_passagers,capacite_bus,type_bus,jour_semaine,periode_depart,condition_route,carburant_litre,satisfaction_client
0,1,Tsévié,Tsévié,56.0,7.2,163.0,8847.0,52.0,50.0,Climatisé,Dimanche,Après-midi,Bonne,43.4,3
1,2,Sokodé,Tsévié,NaN,2.9,124.0,9401.0,39.0,NaN,Standard,Dimanche,NaN,Moyenne,73.7,4
2,3,Dapaong,Sokodé,496.0,1.6,163.0,9228.0,56.0,NaN,Standard,Dimanche,Soir,Bonne,26.5,2
3,4,Sokodé,Lomé,463.0,8.8,88.0,3618.0,NaN,NaN,VIP,Jeudi,Matin,Mauvaise,42.5,4
4,5,Kara,Dapaong,130.0,3.4,32.0,7518.0,67.0,50.0,VIP,Dimanche,Après-midi,Mauvaise,21.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Lomé,NaN,428.0,9.1,137.0,1851.0,33.0,50.0,Standard,Lundi,Matin,Moyenne,38.2,4
1996,1997,Tsévié,Tsévié,406.0,NaN,NaN,6832.0,68.0,70.0,Standard,Dimanche,Après-midi,Moyenne,62.7,3
1997,1998,Atakpamé,Sokodé,615.0,2.2,28.0,3754.0,9.0,50.0,Standard,Vendredi,Soir,NaN,46.0,1
1998,1999,Tsévié,Tsévié,428.0,11.7,0.0,4182.0,14.0,30.0,Climatisé,Lundi,Matin,Bonne,18.7,4
1999,2000,Atakpamé,Tsévié,458.0,7.2,77.0,6570.0,8.0,40.0,VIP,Vendredi,Après-midi,Moyenne,76.3,1

# **Gérer valeurs manquantes**

In [9]:
# Corriger les incohérences
# Plus de passagers que de places
df = df[df['nb_passagers'] <= df['capacite_bus']]

In [10]:
# Retard négatif
df.loc[df['retard_min'] < 0, 'retard_min'] = 0

In [11]:
# Distance nulle avec villes différentes
df = df[df['distance_km'] > 0]

In [12]:
# Capacité bus = 0
df = df[df['capacite_bus'] > 0]

### **Créer de nouvelles variables**

In [13]:
# Taux de remplissage
df['taux_remplissage'] = df['nb_passagers'] / df['capacite_bus']

In [14]:
# Retard par km
df['retard_par_km'] = df['retard_min'] / df['distance_km']

In [15]:
# Retard par heure théorique
df['retard_par_heure'] = df['retard_min'] / df['duree_prevue_h']

In [16]:
# Consommation par km
df['conso_par_km'] = df['carburant_litre'] / df['distance_km']

In [17]:
# Recette du trajet
df['recette'] = df['prix_billet'] * df['nb_passagers']

### **Préparer les données pour le modèle**

In [18]:
# variables numériques
# variables catégorielles
num_features = df.select_dtypes(include=['int64','float64']).columns
cat_features = df.select_dtypes(include=['object']).columns

### **Construire un pipeline complet (automatisé)**

In [19]:
# Transformer numérique
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

In [20]:
numeric_transformer

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [21]:
# Transformer catégoriel
from sklearn.preprocessing import OneHotEncoder

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

In [27]:
categorical_transformer

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder', OneHotEncoder(handle_unknown='ignore'))])

In [22]:
# ColumnTransformer
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, num_features),
        ('cat', categorical_transformer, cat_features)
    ]
)

In [28]:
preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 Index(['trajet_id', 'distance_km', 'duree_prevue_h', 'retard_min',
       'prix_billet', 'nb_passagers', 'capacite_bus', 'carburant_litre',
       'taux_remplissage', 'retard_par_km', 'retard_par_heure', 'conso_par_km',
       'recette'],
      dtype='object')),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 Index(['ville_depart', 'ville_arrivee', 'type_bus', 'jour_semaine',
       'periode_depart', 'condition_route'],
      dtype='object'))])

### **Construire un modèle prédictif**

In [23]:
# prédire la satisfaction client
X = df.drop('satisfaction_client', axis=1)
y = df['satisfaction_client']

In [24]:
# Division entraînement / test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [30]:
print(train_test_split(X_train, y_train))
print(train_test_split(X_test, y_test))

[      trajet_id ville_depart ville_arrivee  distance_km  duree_prevue_h  \
1304       1305         Lomé          Lomé        552.0             8.0
1273       1274       Tsévié          Kara        418.0            10.1
894         895       Tsévié        Tsévié        325.0             2.6
1261       1262     Atakpamé        Sokodé        329.0             1.6
1647       1648       Sokodé          Lomé        425.0             6.6
...         ...          ...           ...          ...             ...
1746       1747      Dapaong       Dapaong        110.0             2.4
331         332         Kara          Kara        130.0             6.2
71           72      Dapaong      Atakpamé        609.0             1.7
1140       1141     Atakpamé       Dapaong        561.0             6.0
207         208       Tsévié          Lomé        139.0            10.3

      retard_min  prix_billet  nb_passagers  capacite_bus   type_bus  \
1304        89.0       8197.0          27.0          60.0        VIP
1273        80.0       3361.0          48.0          70.0        VIP
894        172.0       4476.0          49.0          60.0  Climatisé
1261       168.0      10750.0          35.0          70.0  Climatisé
1647        32.0       6588.0          45.0          60.0  Climatisé
...          ...          ...           ...           ...        ...
1746         NaN      10368.0           5.0          30.0  Climatisé
331         48.0       5568.0           9.0          60.0        VIP
71         177.0       7567.0          23.0          30.0        NaN
1140       111.0       2998.0          12.0          50.0        VIP
207         82.0      11274.0          18.0          70.0        VIP

     jour_semaine periode_depart condition_route  carburant_litre  \
1304     Dimanche           Soir         Moyenne             61.2
1273       Samedi     Après-midi           Bonne             21.9
894           NaN          Matin           Bonne             51.4
1261        Jeudi     Après-midi        Mauvaise             73.3
1647        Mardi          Matin        Mauvaise             55.9
...           ...            ...             ...              ...
1746        Lundi            NaN           Bonne             42.6
331      Mercredi     Après-midi           Bonne             35.9
71          Lundi           Soir           Bonne             39.5
1140        Lundi            NaN         Moyenne             43.0
207      Vendredi          Matin           Bonne             57.8

      taux_remplissage  retard_par_km  retard_par_heure  conso_par_km  \
1304          0.450000       0.161232         11.125000      0.110870
1273          0.685714       0.191388          7.920792      0.052392
894           0.816667       0.529231         66.153846      0.158154
1261          0.500000       0.510638        105.000000      0.222796
1647          0.750000       0.075294          4.848485      0.131529
...                ...            ...               ...           ...
1746          0.166667            NaN               NaN      0.387273
331           0.150000       0.369231          7.741935      0.276154
71            0.766667       0.290640        104.117647      0.064860
1140          0.240000       0.197861         18.500000      0.076649
207           0.257143       0.589928          7.961165      0.415827

       recette
1304  221319.0
1273  161328.0
894   219324.0
1261  376250.0
1647  296460.0
...        ...
1746   51840.0
331    50112.0
71    174041.0
1140   35976.0
207   202932.0

[637 rows x 19 columns],       trajet_id ville_depart ville_arrivee  distance_km  duree_prevue_h  \
136         137      Dapaong        Tsévié        103.0             2.7
1982       1983         Kara        Sokodé        334.0             2.7
1965       1966       Sokodé          Kara         85.0             2.1
610         611       Sokodé       Dapaong        564.0             2.0
875         876     Atakpamé       Dapaong        482.0             9.7
...         ...          ...           ...          ...             ...
1996       1997       Tsévié        Tsévié        406.0             NaN
902         903       Tsévié      Atakpamé        135.0             7.1
1747       1748     Atakpamé       Dapaong        370.0             9.1
14           15         Lomé      Atakpamé        185.0             7.0
1595       1596       Sokodé          Lomé         76.0             8.6

      retard_min  prix_billet  nb_passagers  capacite_bus   type_bus  \
136         15.0       8325.0          13.0          70.0   Standard
1982       161.0          NaN          28.0          50.0        VIP
1965         NaN       6080.0          11.0          30.0        VIP
610         76.0       4953.0           8.0          30.0        VIP
875          NaN       3679.0           7.0          50.0        VIP
...          ...          ...           ...           ...        ...
1996         NaN       6832.0          68.0          70.0   Standard
902        162.0       9327.0          13.0          50.0   Standard
1747        47.0       6209.0          24.0          60.0        NaN
14          53.0       2619.0          21.0          30.0  Climatisé
1595       125.0       5038.0          17.0          40.0        NaN

     jour_semaine periode_depart condition_route  carburant_litre  \
136        Samedi           Soir        Mauvaise             27.2
1982     Vendredi     Après-midi        Mauvaise             65.1
1965        Jeudi           Soir        Mauvaise             61.5
610         Lundi           Soir        Mauvaise             63.5
875         Lundi     Après-midi           Bonne              NaN
...           ...            ...             ...              ...
1996     Dimanche     Après-midi         Moyenne             62.7
902           NaN     Après-midi        Mauvaise             59.3
1747       Samedi          Matin             NaN              NaN
14       Vendredi            NaN         Moyenne              NaN
1595        Mardi           Soir         Moyenne             46.1

      taux_remplissage  retard_par_km  retard_par_heure  conso_par_km  \
136           0.185714       0.145631          5.555556      0.264078
1982          0.560000       0.482036         59.629630      0.194910
1965          0.366667            NaN               NaN      0.723529
610           0.266667       0.134752         38.000000      0.112589
875           0.140000            NaN               NaN           NaN
...                ...            ...               ...           ...
1996          0.971429            NaN               NaN      0.154433
902           0.260000       1.200000         22.816901      0.439259
1747          0.400000       0.127027          5.164835           NaN
14            0.700000       0.286486          7.571429           NaN
1595          0.425000       1.644737         14.534884      0.606579

       recette
136   108225.0
1982       NaN
1965   66880.0
610    39624.0
875    25753.0
...        ...
1996  464576.0
902   121251.0
1747  149016.0
14     54999.0
1595   85646.0

[213 rows x 19 columns], 1304    1
1273    3
894     3
1261    2
1647    4
       ..
1746    5
331     3
71      3
1140    5
207     1
Name: satisfaction_client, Length: 637, dtype: int64, 136     4
1982    3
1965    4
610     5
875     4
       ..
1996    3
902     4
1747    5
14      1
1595    3
Name: satisfaction_client, Length: 213, dtype: int64]
[      trajet_id ville_depart ville_arrivee  distance_km  duree_prevue_h  \
152         153         Lomé           NaN        285.0             6.0
182         183         Kara          Lomé        534.0            11.4
1814       1815       Tsévié        Tsévié        566.0             9.8
270         271       Tsévié          Kara        371.0             4.6
1751       1752       Sokodé        Tsévié        602.0             NaN
...         ...          ...           ...          ...             ...
826         827     Atakpamé        Sokodé        539.0             8.0
656         657       Sokodé          Kara        317.0             5.8
842         843         Lomé      Atakpamé        232.0             3.7
1191       1192         Lomé          Kara         66.0             2.1
1822       1823       Sokodé          Kara        434.0             NaN

      retard_min  prix_billet  nb_passagers  capacite_bus   type_bus  \
152        128.0       6052.0          30.0          30.0  Climatisé
182        150.0       2799.0          42.0          50.0   Standard
1814       164.0       1782.0          53.0          70.0   Standard
270        119.0       9012.0          15.0          50.0        NaN
1751        19.0       2489.0          12.0          30.0  Climatisé
...          ...          ...           ...           ...        ...
826         98.0       3584.0           8.0          50.0  Climatisé
656        103.0       5695.0          30.0          30.0  Climatisé
842         55.0       7426.0          55.0          70.0        VIP
1191       131.0       4777.0          51.0          70.0   Standard
1822       178.0       9119.0          27.0          50.0        VIP

     jour_semaine periode_depart condition_route  carburant_litre  \
152      Mercredi     Après-midi           Bonne             58.3
182      Mercredi           Soir         Moyenne             48.5
1814        Jeudi     Après-midi           Bonne             21.4
270      Dimanche          Matin           Bonne             57.7
1751        Mardi            NaN        Mauvaise             36.0
...           ...            ...             ...              ...
826      Mercredi     Après-midi           Bonne             41.7
656        Samedi          Matin        Mauvaise             28.9
842         Lundi     Après-midi        Mauvaise             53.7
1191     Dimanche     Après-midi         Moyenne             77.6
1822        Jeudi           Soir        Mauvaise             39.8

      taux_remplissage  retard_par_km  retard_par_heure  conso_par_km  \
152           1.000000       0.449123         21.333333      0.204561
182           0.840000       0.280899         13.157895      0.090824
1814          0.757143       0.289753         16.734694      0.037809
270           0.300000       0.320755         25.869565      0.155526
1751          0.400000       0.031561               NaN      0.059801
...                ...            ...               ...           ...
826           0.160000       0.181818         12.250000      0.077365
656           1.000000       0.324921         17.758621      0.091167
842           0.785714       0.237069         14.864865      0.231466
1191          0.728571       1.984848         62.380952      1.175758
1822          0.540000       0.410138               NaN      0.091705

       recette
152   181560.0
182   117558.0
1814   94446.0
270   135180.0
1751   29868.0
...        ...
826    28672.0
656   170850.0
842   408430.0
1191  243627.0
1822  246213.0

[159 rows x 19 columns],       trajet_id ville_depart ville_arrivee  distance_km  duree_prevue_h  \
181         182         Kara      Atakpamé        510.0             5.2
1126       1127          NaN          Lomé        292.0             9.6
23           24     Atakpamé       Dapaong         68.0             8.6
1772       1773      Dapaong        Tsévié        111.0            10.4
888         889      Dapaong        Tsévié        605.0             4.8
1820       1821       Sokodé          Lomé         72.0             NaN
111         112         Lomé          Kara        482.0             9.6
524         525      Dapaong          Lomé        232.0             5.3
1343       1344       Tsévié        Tsévié        169.0             NaN
496         497       Sokodé          Kara        458.0             6.5
348         349         Lomé      Atakpamé        587.0             7.9
1519       1520     Atakpamé          Lomé        317.0             5.6
1018       1019       Sokodé       Dapaong        458.0            10.0
488         489      Dapaong        Tsévié        558.0             7.4
402         403      Dapaong          Kara        112.0            11.9
1008       1009      Dapaong          Kara        453.0             8.4
921         922     Atakpamé          Lomé        241.0             4.1
869         870      Dapaong        Tsévié        273.0             6.7
1632       1633     Atakpamé        Sokodé        102.0             3.4
103         104         Kara       Dapaong        203.0             4.5
1710       1711       Tsévié          Kara        456.0             NaN
338         339      Dapaong        Tsévié        551.0             3.9
174         175       Sokodé          Lomé        337.0             8.2
1794       1795       Sokodé          Kara        215.0            11.6
1955       1956         Kara      Atakpamé        314.0             8.4
1804       1805      Dapaong          Lomé        485.0             NaN
608         609     Atakpamé          Kara        605.0             6.0
634         635         Lomé        Tsévié        241.0             7.7
1426       1427     Atakpamé          Kara         78.0             3.6
1322       1323       Sokodé       Dapaong        572.0            10.8
909         910       Sokodé      Atakpamé         89.0             7.9
1574       1575         Kara       Dapaong        528.0             9.7
1134       1135         Kara           NaN        454.0             9.8
558         559      Dapaong          Lomé        399.0             4.9
1661       1662      Dapaong       Dapaong        190.0            10.2
858         859       Sokodé          Lomé        444.0            11.8
1255       1256         Lomé          Lomé        641.0             NaN
1160       1161       Tsévié      Atakpamé        245.0             8.2
1910       1911       Tsévié          Kara        459.0             6.9
265         266      Dapaong        Sokodé        497.0             8.3
876         877     Atakpamé          Kara        581.0             8.6
1315       1316       Tsévié      Atakpamé        207.0             4.8
55           56     Atakpamé      Atakpamé        408.0             5.7
1735       1736     Atakpamé      Atakpamé        304.0             6.6
1713       1714          NaN        Sokodé        427.0            10.2
56           57       Tsévié      Atakpamé        441.0             9.7
1182       1183     Atakpamé      Atakpamé        216.0             7.4
519         520       Tsévié          Lomé        236.0             NaN
139         140      Dapaong          Lomé        229.0            10.4
92           93       Sokodé        Sokodé        640.0             3.3
581         582         Lomé        Tsévié        309.0             NaN
1336       1337       Sokodé        Tsévié        172.0             NaN
1078       1079       Tsévié        Sokodé        536.0             1.9
1979       1980          NaN           NaN        256.0             2.6

      retard_min  prix_billet  nb_passagers  capacite_bus   type_bus  \
181         92.0      11930.0          26.0          40.0   Standard
1126       114.0       2796.0          68.0          70.0        VIP
23         110.0       6809.0          63.0          70.0   Standard
1772         0.0       3261.0          22.0          70.0  Climatisé
888         73.0      10049.0          51.0          70.0   Standard
1820       157.0       3627.0          29.0          30.0   Standard
111        173.0       5575.0          23.0          40.0        VIP
524         95.0       6138.0          24.0          60.0        VIP
1343       164.0          NaN          26.0          70.0   Standard
496        131.0       4102.0          18.0          50.0        VIP
348         85.0      10285.0          12.0          30.0        VIP
1519       168.0       5989.0           6.0          40.0   Standard
1018       175.0       2059.0          46.0          50.0        VIP
488        103.0       3966.0           7.0          50.0   Standard
402         36.0          NaN          48.0          60.0  Climatisé
1008       146.0          NaN          20.0          60.0        NaN
921        156.0       4716.0          23.0          30.0        VIP
869         20.0       5061.0          25.0          40.0        VIP
1632       172.0       5999.0          34.0          60.0  Climatisé
103         71.0       8666.0          20.0          30.0   Standard
1710         NaN       8096.0          35.0          50.0        VIP
338         16.0       2199.0           5.0          30.0        VIP
174         48.0       4892.0           6.0          50.0  Climatisé
1794         NaN       3791.0          29.0          50.0  Climatisé
1955         0.0       4040.0          12.0          40.0   Standard
1804        36.0       2272.0          34.0          70.0  Climatisé
608         56.0       9563.0          51.0          60.0  Climatisé
634        141.0       7508.0          24.0          30.0   Standard
1426        86.0       6372.0          10.0          30.0  Climatisé
1322       146.0       1797.0          35.0          50.0        NaN
909         41.0       3828.0          22.0          30.0   Standard
1574       125.0       6519.0          50.0          70.0   Standard
1134        44.0       3595.0          21.0          30.0        VIP
558        165.0       5197.0          13.0          70.0        VIP
1661       170.0       4582.0          40.0          40.0  Climatisé
858         10.0          NaN          34.0          60.0  Climatisé
1255        31.0       4963.0          48.0          50.0   Standard
1160         NaN       3086.0          11.0          50.0  Climatisé
1910       118.0       2117.0          58.0          60.0        NaN
265          3.0       6284.0          56.0          60.0  Climatisé
876         16.0       7572.0          41.0          60.0   Standard
1315       121.0      10588.0           7.0          60.0  Climatisé
55           1.0       7542.0          13.0          70.0   Standard
1735        22.0       9718.0          54.0          70.0        VIP
1713         NaN       6254.0          63.0          70.0  Climatisé
56         178.0      11144.0          16.0          60.0   Standard
1182        68.0       3056.0          33.0          40.0  Climatisé
519         19.0       5552.0          12.0          50.0        VIP
139        177.0      10413.0           7.0          50.0   Standard
92         105.0       4301.0           8.0          60.0        NaN
581        113.0          NaN          33.0          60.0        VIP
1336        14.0       6519.0          23.0          30.0  Climatisé
1078        67.0       7802.0          62.0          70.0   Standard
1979        45.0       7723.0          36.0          60.0        VIP

     jour_semaine periode_depart condition_route  carburant_litre  \
181         Lundi          Matin         Moyenne             76.3
1126       Samedi           Soir        Mauvaise             46.9
23       Mercredi     Après-midi        Mauvaise             15.2
1772     Vendredi          Matin             NaN             27.1
888      Vendredi     Après-midi           Bonne             42.3
1820        Mardi            NaN           Bonne             36.0
111         Jeudi     Après-midi           Bonne             21.8
524      Mercredi           Soir        Mauvaise             69.2
1343        Mardi           Soir             NaN             64.6
496        Samedi           Soir             NaN             16.8
348           NaN          Matin         Moyenne             69.0
1519       Samedi           Soir           Bonne             78.1
1018       Samedi           Soir         Moyenne             46.0
488      Mercredi           Soir             NaN             24.7
402        Samedi          Matin         Moyenne             46.9
1008        Mardi          Matin         Moyenne             30.2
921         Mardi          Matin           Bonne              NaN
869      Dimanche     Après-midi             NaN             23.0

In [25]:
# Choisir un modèle
# Prenons Random Forest
from sklearn.ensemble import RandomForestRegressor

model = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('regressor', RandomForestRegressor())
])

In [29]:
print(model)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['trajet_id', 'distance_km', 'duree_prevue_h', 'retard_min',
       'prix_billet', 'nb_passagers', 'capacite_bus', 'carburant_litre',
       'taux_remplissage', 'retard_par_km', 'retard_par_heure', 'conso_par_km',
       'recette'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['ville_depart', 'ville_arrivee', 'type_bus', 'jour_semaine',
       'periode_depart', 'condition_route'],
      dtype='object'))])),
                ('regressor', RandomForestRegressor())])

In [26]:
# Entraîner le modèle

# Correctement définir les listes de features à partir de X (sans la cible)
num_features = X.select_dtypes(include=['int64', 'float64']).columns
cat_features = X.select_dtypes(include=['object']).columns

# Recréer le ColumnTransformer avec les listes de features corrigées
# (Les transformers individuels comme numeric_transformer et categorical_transformer
# sont supposés être correctement définis dans les cellules précédentes.)
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, num_features),
        ('cat', categorical_transformer, cat_features)
    ]
)

# Recréer le pipeline du modèle avec le preprocessor mis à jour
# (RandomForestRegressor et Pipeline sont supposés être importés.)
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
model = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('regressor', RandomForestRegressor())
])

model.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['trajet_id', 'distance_km', 'duree_prevue_h', 'retard_min',
       'prix_billet', 'nb_passagers', 'capacite_bus', 'carburant_litre',
       'taux_remplissage', 'retard_par_km', 'retard_par_heure', 'conso_par_km',
       'recette'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['ville_depart', 'ville_arrivee', 'type_bus', 'jour_semaine',
       'periode_depart', 'condition_route'],
      dtype='object'))])),
                ('regressor', RandomForestRegressor())])